spring.application.name=park-finder

# H2 en archivo local (persiste entre reinicios)
spring.datasource.url=jdbc:h2:file:./data/parkdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=false
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# SQL
spring.sql.init.mode=never

# Servidor
spring.main.web-application-type=servlet
server.port=8098

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false
